# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:  
 
 workflow_dispatch:

   inputs:
      link:
        description: 'Enter DirectLink To Download ⚡️'
        required: true
      filename: 
        description: 'enter full file name that is on torrent'  
        required: true
        
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: MAGNET CONVERSION 
        run: | 
            export VAR="${{ github.event.inputs.link }}"
            printenv VAR
             pip3 install torrentp
               python3 torrent.py
               zip -r file.zip "${{github.event.inputs.filename }}"
               sudo apt install jq -y
               curl -F "file=@file.zip" https://api.anonfiles.com/upload >>outputs.txt
               
      - name: Click To View Link
        run: |
             echo "LINKS ARE COMING WAIT FOR 5 SECONDS!!!"
             sleep 5
             
             
             grep -o -E "https?://[][[:alnum:]._~:/?#@!$&'()*+,;%-]+" outputs.txt  >>link.txt
             
             echo "$(<link.txt )"
             
             echo "LONG LIVE KINDEVILS"
           
              
                
